# -*- coding: utf-8 -*-
"""Week_5_Graph_Path.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TiJoJzCOC3elOplInrz2QQH2NjbZOR_4

finding lognest path in the graph is complex while in DAG(Directed Acyclic Graph) it is simple by taking adjecency list.

If we have the -ve cycle in the graph then their is no sencse in the  shortest path we can not find the shortest path
"""

### implementaion of the weighted  graph
## adjecency list using dist
class adjListDist:
  def __init__(self,adj=None):
    self.adj = adj

  def addEdge(self,i,j,w):
    if i in self.adj:
      self.adj[i].append((j,w))
    else:
      self.adj[i] = [(j,w)]

    if j in self.adj:
      self.adj[j].append((i,w))
    else:
      self.adj[j] = [(i,w)]

  def displayList(self):
    for node in self.adj:
          print(f"{node}:", self.adj[node])

  def showList(self):
    return self.adj

## list format :- {node : [(connectes_node,weights)....],}
dist ={}
adjcencyList = adjListDist(dist)
adjcencyList.addEdge(2,3,10)
adjcencyList.addEdge(2,4,20)
adjcencyList.addEdge(1,2,5)
adjcencyList.addEdge(1,3,8)
dist

graphDist = {}
graph = adjListDist(graphDist)

graph.addEdge(1, 2, 2)
graph.addEdge(1, 3, 5)

graph.addEdge(2, 4, 4)
graph.addEdge(2, 5, 1)

graph.addEdge(3, 5, 2)

graph.addEdge(4, 6, 6)
graph.addEdge(4, 7, 2)

graph.addEdge(5, 7, 3)

graph.addEdge(6, 8, 3)

graph.addEdge(7, 9, 1)

graph.addEdge(8, 9, 4)

graph.addEdge(9, 10, 2)
graphDist

graphDist2 = {}
graph1 = adjListDist(graphDist2)

graph1.addEdge(1, 2, 4)
graph1.addEdge(1, 3, 2)

graph1.addEdge(2, 4, 1)
graph1.addEdge(2, 5, 3)

graph1.addEdge(3, 5, 5)

graph1.addEdge(4, 6, 7)
graph1.addEdge(4, 7, 2)

graph1.addEdge(5, 7, 1)

graph1.addEdge(6, 8, 1)

graph1.addEdge(7, 8, 2)

from IPython.core.interactiveshell import dis
(distance,visited) =({2: 0, 3: 81, 4: 81, 1: 81}, {2: True, 3: False, 4: False, 1: False})
nextd =   # min([distance[v] for v in dist.keys() if not visited[v]])
nextvlist = [v for v in dist.keys() if not visited[v] and distance[v] == nextd]
nextv =  min(nextvlist)
print(nextd)
'''visited[nextv] = True
print(dist[1])
for (d,v) in dist[nextv]:
      if not visited[v]:
        distance[v] = min(distance[v],distance[nextv],d)
distance,visited'''

## Dijkstra algo only for +ve weight
def dijkestra(u,weiAdjList={}):
  infinity = 1+len(weiAdjList.keys())*max([d for i in weiAdjList
                                          for v,d in weiAdjList.get(i)])
  print(infinity)
  (visited,distance) = ({},{})
  for key in weiAdjList.keys():
     visited[key],distance[key] = False,infinity

  for key in weiAdjList.keys():
    nextd = min([distance[v] for v in weiAdjList.keys() if not visited[v]])
    nextvlist = [v for v in weiAdjList.keys() if not visited[v] and distance[v] == nextd]
    if nextvlist == []:
      break
    nextv = min(nextvlist)
    visited[nextv] = True
    for (v,d) in weiAdjList[nextv]:
      if not visited[v]:
        distance[v] = min(distance[v],distance[nextv])

  distance[u] = 0

  return distance,visited

"""## single source shortest path"""

## Dijkstra algo only for +ve weight
def dijkestraUpdate(u,weiAdjList={}):
  infinity = 1+len(weiAdjList.keys())*max([d for i in weiAdjList
                                          for v,d in weiAdjList.get(i)])
  (visited,distance) = ({},{})
  for key in weiAdjList.keys():
     visited[key],distance[key] = False,infinity
  visited[u] = True
  distance[u] = 0
  minQueue = []
  minQueue.append((u,0))
  #print(f"before queue : {minQueue}")
  i = 0
  while minQueue:
    minPop = minQueue.pop(0)
    #print(f"after minpop {i} an sort {minPop}")
    #print(f"after pop {i} an sort {minQueue}")
    #print(f"connected node to pop {weiAdjList[minPop[0]]}")
    #print(visited)
    updateAdjNodeList = [t for t in weiAdjList[minPop[0]] if t[0] != minPop[0]]
    for key in updateAdjNodeList:
      #print(f"orignal distance {distance}")
      if not visited[key[0]] and key not in minQueue:
        visited[key[0]] = True
        updateDist =  key[1] + minPop[1]
        distance[key[0]] = updateDist
        if key[0] in [6,8,7,5]:
           print(f"Inside not visited key {key} total dist from source {key[1] + minPop[1]}")
        minQueue.append((key[0],updateDist))
      elif distance[key[0]] + minPop[1] < distance[key[0]] and key not in minQueue:
        if key[0] in [6,8,7,5]:
          print(f"Inside visited key {key} total dist from source {distance[key[0]] + minPop[1]}")
        distance[key[0]] = (distance[key[0]] + minPop[1])
        minQueue.append((key[0],distance[key[0]] + minPop[1]))
        if key[0] in [6,8,7,5]:
         print(f"key {key} total dist from source {key[1] + minPop[1]}")
    visited[minPop[0]] = True
    minQueue = sorted(minQueue,key=lambda x : x[1])


  return distance,visited

#smalldist = dijkestraUpdate(2,dist)
smalldist_2 = dijkestraUpdate(5,graphDist)
smalldist_2

#smalldist = dijkestraUpdate(2,dist)
smalldist_2 = dijkestraUpdate(3,graphDist2)
smalldist_2

{
  1: 3,
  2: 1,
  3: 2,
  4: 5,
  5: 0,
  6: 11,
  7: 3,
  8: 14,
  9: 4,
  10: 6
}

test = [(1, 10), (3, 7), (4, 5)]
if (2, 0) not in test:
  print(True)
test_sort = test.pop(0)
print(test_sort)
print(test)

'''def dijkestraUpdate(u,weiAdjList={}):
  infinity = 1+len(weiAdjList.keys())*max([d for i in weiAdjList
                                          for v,d in weiAdjList.get(i)])
  print(infinity)
  (visited,distance) = ({},{})
  for key in weiAdjList.keys():
     visited[key],distance[key] = False,infinity
  visited[u] = True
  distance[u] = 0
  minD = ()
  for key in weiAdjList.keys():
    if visited[key]:
      print(True)
    else:
      for v in range(len(weiAdjList[key]) -1 ):
        if weiAdjList[key][v][1] < weiAdjList[key][v + 1][1]:
          minD = weiAdjList[key][v]

        if v == len(weiAdjList[key]) - 2 and minD == 0:
          minD = weiAdjList[key][-1]
      print(minD)
      #visited[minD[0]] = True
      #distance[minD[0]] = minD[1]
      minD = 0



  for key in weiAdjList.keys():
    print(key)
    print(weiAdjList[key])
    nextd = []
    for v,d in weiAdjList[key]:
      minD = d
    minNext = []
    print((nextd))
    nextd = min([distance[v] for v in weiAdjList[key] if not visited[v]])
    print(f"nextd {nextd}")
    nextvlist = [v for v in weiAdjList.keys() if not visited[v] and distance[v] == nextd]
    print(f"nextv list :{nextvlist}")
    if visited == []:
      break
    nextv = min(nextvlist)
    visited[nextv] = True
    for (v,d) in weiAdjList[nextv]:
      if not visited[v]:
        distance[v] = min(distance[v],distance[nextv])


  return distance,visited'''

class solution:
  def shortestPath(self, n :int,edges: List[List[int]],src:int) -> Dist:
    adj = {}
    for i in range(n):
      adj[i] = []

    for src,dist,weight in edges:
      adj[src].apppend([dist,weight])

    shortest = {}
    minHeap = [[0,src]]
    while minHeap:
      w1,h1 = heapq.heappop(minHeap)
      if n1 in shortest:
        continue
      shortest[n1] = w1

      for n2,w2 in adj[n1]:
        if n2 not in shortest:
          heapq.heappush(minheap,[w1 + w2 ,n2])

for i in range(n):
  if i not in shortest:
    shortest[i] = -1



    return shortest

distance[u] = 0
  visited[u] = True
  shortest = {}
  vHeap = []
  vHeap.extend(weiAdjList[u])
  dMin = ()
  for i in range(len(vHeap) -1):
    if vHeap[i][1] < vHeap[i+1][1]:
      dMin = vHeap[i]
  shortest[dMin[0]] = dMin[1]
  print(f"shortest path :{shortest}")